//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class block
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public block()
        {
            this.property = new HashSet<property>();
        }
    
        public int id { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> society_id { get; set; }
        public Nullable<int> phase_id { get; set; }
        public string name { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
    
        public virtual city city { get; set; }
        public virtual phase phase { get; set; }
        public virtual society society { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<property> property { get; set; }
    }
}
