//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public property()
        {
            this.inquiry = new HashSet<inquiry>();
        }
    
        public int id { get; set; }
        public string purpose { get; set; }
        public Nullable<int> type_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> society_id { get; set; }
        public Nullable<int> phase_id { get; set; }
        public Nullable<int> block_id { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public Nullable<double> area { get; set; }
        public string area_unit { get; set; }
        public Nullable<double> area_in_marla { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<bool> is_corner { get; set; }
        public string image { get; set; }
        public string owner_name { get; set; }
        public string owner_contact1 { get; set; }
        public string owner_contact2 { get; set; }
        public Nullable<bool> is_available { get; set; }
        public string dealer_id { get; set; }
        public string affidavit_price { get; set; }
        public string price_with_comma { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<bool> isSelected { get; set; }
        public string userId { get; set; }
        public string type_name { get; set; }
        public string city_name { get; set; }
        public string society_name { get; set; }
        public string phase_name { get; set; }
        public string block_name { get; set; }
        public string plot_no { get; set; }
        public string plot_type { get; set; }
        public string affidavit_price_with_comma { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual block block { get; set; }
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inquiry> inquiry { get; set; }
        public virtual phase phase { get; set; }
        public virtual property_type property_type { get; set; }
        public virtual society society { get; set; }
    }
}
